---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_path: test/shared

platforms:
  - name: centos-7.1
 # - name: ubuntu-14.04

suites:
  - name: default
    run_list:
       - recipe[logstash_simple::default]
    attributes:
